#!/bin/sh

for FILE in *.webm
do
  BASE=`basename "${FILE}" .webm`

  SRC=`echo $BASE | sed 's/ /\ /g'`.webm
  DST=`echo $BASE | sed 's/ /\ /g'`.mp4

  [ -r "${DST}" ] && rm "${DST}"

  ffmpeg -i "${SRC}" "${DST}"
done
